import { Logger } from "../utils/logger.js"

export class Guardrails {
  private promotedThisSession = 0

  constructor(
    private readonly maxPerSession: number = 5,
    private readonly logger: Logger = new Logger(false),
  ) {}

  canPromote(): boolean {
    return this.promotedThisSession < this.maxPerSession
  }

  recordPromotion(): void {
    this.promotedThisSession += 1
    this.logger.info(`Guardrail promotion ${this.promotedThisSession}/${this.maxPerSession}`)
  }

  getCount(): number {
    return this.promotedThisSession
  }

  reset(): void {
    this.promotedThisSession = 0
  }

  isAutoGenerated(frontmatter: Record<string, unknown>): boolean {
    return frontmatter["auto-generated"] === true
  }

  validateSkill(frontmatter: Record<string, unknown>): { allowed: boolean; reason?: string } {
    if (frontmatter["auto-generated"] !== true) {
      return { allowed: false, reason: "skill must have auto-generated: true" }
    }
    return { allowed: true }
  }

  checkWriteAllowed(slug: string, frontmatter: Record<string, unknown>): boolean {
    if (!this.canPromote()) {
      this.logger.warn(`Guardrail blocked ${slug}: max ${this.maxPerSession}/session`)
      return false
    }
    if (frontmatter["auto-generated"] !== true && frontmatter["auto-generated"] !== undefined) {
      this.logger.warn(`Guardrail blocked ${slug}: not auto-generated`)
      return false
    }
    return true
  }
}
